[package]
name = "tsq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tree-sitter = "0.20.9"
glob = "0.3.1"
libloading = "0.7"
json = "0.12.4"
